### ISSUE TITLE
Can I swap/use custom keybindings default action and alternative action?

### ISSUE THREAD

**Issue by zizhengwu** [zsh-users/zaw#105]
Is it possible to make `accept-search` the default action and `accept-line` the alternative action? Also, I'm wondering if it's possible to use custom keybindings other than `meta + enter`--sadly I couldn't find out how to send `meta + enter` in iTerm 2 on macOS.

**Comment by kenbeese** [comment]
I'm changing the keybinding of `accept-search`  to `ctrl + e` by `bindkey -M filterselect '^E' accept-search` in `~/.zshrc`. Please try it.

**Comment by zizhengwu** [comment]
@kenbeese thank you so much! I added the following to my zshrc
```
bindkey -M filterselect '^M' accept-search
```
And `accept-search` becomes the default action (press enter)
