### ISSUE TITLE
Ctrl-I (^I)

### ISSUE THREAD

**Issue by wernight** [zsh-users/zaw#50]
I found Ctrl+X, ;, Ctrl+I to provide a feature that I didn't see on the README. Would be nice to make it more visible.

**Comment by willghatch** [comment]
Hmm, `C-X ;` is in the readme (starts zaw), and `C-i` in the terminal is always the same as the tab key, so that's also in the readme.  Maybe this issue is just outdated...  I'll close it, but if I'm missing something, you can open it again or send another message.
