### ISSUE TITLE
zaw-history not respecting 'hist_find_no_dups'

### ISSUE THREAD

**Issue by jfelchner** [zsh-users/zaw#51]
I have `setopt hist_find_no_dups`, but whenever I search in my history, I see duplicates for all the commands I've run more than once.

I do not want to set `hist_ignore_all_dups` because it's valuable to go back and see a previously executed sequence of commands.  If duplicates are removed, then that sequence of commands becomes modified and it's harder to piece together.

**Comment by jfelchner** [comment]
@termoshtt I see you're doing some commits.  I really, _really_ hope you can merge #54 in.  :grinning:

**Comment by jfelchner** [comment]
@willghatch is there a hold up to merging in @PythonNut's patch?  This has been killing me for over a year.

**Comment by PythonNut** [comment]
@jfelchner doesn't the patch not work?

**Comment by jfelchner** [comment]
@PythonNut yeah, I completely forgot about the comment by @willghatch on the PR.

**Comment by jfelchner** [comment]
@willghatch does this look like it's even doable?  I'd really like to find a solution. :disappointed:

**Comment by PythonNut** [comment]
@willghatch dude, you're awesome.

**Comment by willghatch** [comment]
I tried it a slightly different way and got it working.  The issue was trying to unique-ify the `cands_assoc` array, which broke things.  But it works fine with `candidates` instead of `cands_assoc`.  Note that the history is all out of order now if you use hist_find_no_dups, but that shouldn't matter too much since you're filtering.

**Comment by jfelchner** [comment]
@willghatch you're awesome!!!!!!!! :heart:

**Comment by willghatch** [comment]
@PythonNut @jfelchner I've just changed it to appease #71 so now you need to set:
`zstyle ':filter-select' hist-find-no-dups yes`

I hope everyone is happy with this compromise.

**Comment by jfelchner** [comment]
@willghatch this is perfectly acceptable. Thank you. 😊
