### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by willghatch** [zsh-users/zaw#58]
This repository's latest commit is over a year old, and there are lots of great pull requests.  I really want some of those incorporated(git log, various improvements to git sources, etc), but I don't want to maintain a fork and work to pull all these in.  I'm sure I'm not the only one who would like some of these great features.

If nobody in the zsh-users group has time or desire to go through the pull requests and merge the good ones, I'm happy to do it if you add me to the group.  Or we should find somebody else who is willing.  I just want zaw to stay alive and adopt some of these PRs.

**Comment by termoshtt** [comment]
:+1: 

I am also willing to help maintaining this project,
and to be one of the maintainers if permitted.

**Comment by nakamuray** [comment]
Okay, I'll grant commit privilege to you (willghatch and termoshtt).
Do it well, please.

**Comment by termoshtt** [comment]
Thanks.
I confirm that I became a collaborator.
I will start to review PRs on this weekend.

**Comment by willghatch** [comment]
Thanks, I can also confirm that I'm a collaborator.  I've merged my
favorite PR (from @termoshtt actually) that I tested a long time ago and
have wanted since then, and I'm starting to review some more.
