### ISSUE TITLE
Keybindings for alternative options

### ISSUE THREAD

**Issue by mihaiolteanu** [zsh-users/zaw#88]
Is there a way to set a keybinding for any of the alternative options?
I know about the Meta-Enter for the first alternative option, but can you set other keys for the other options?

**Comment by willghatch** [comment]
Not currently.  Pull requests welcome.

**Comment by shanematley** [comment]
I have just submitted a pull request (#96) for a feature similar to this. I haven't done a pull request before, so I'm not sure how to link it to this feature request. My change isn't for adding additional keys, but instead allows for configuration of the default action on "Enter" and the alternative action on "Meta-enter". To make discovery clearer, I also added the text " (Enter)" and " (Meta-enter)" to the actions that are configured.

**Comment by termoshtt** [comment]
Resolved by #96
