### ISSUE TITLE
zle: widgets can only be called with ZLE is active

### ISSUE THREAD

**Issue by brandonsturgeon** [zsh-users/zaw#89]
Hi there, I'm trying to use Zaw for the first time. I've followed the installation directions. I cloned zaw to a folder in my home directory, and then sourced `zaw.zsh` from my `.zshrc`.

When I try to run `zaw-history` (or any `zaw*` command) directly, I get : `zaw-history:zle: widgets can only be called when ZLE is active`. Additionally, when I press `ctrl-x`, nothing happens.

Even if I source `zaw.zsh` in my terminal, `ctrl-x` still doesn't work.

Any suggestions?

**Comment by willghatch** [comment]
You need to type `ctrl-x` followed by `;`.  Alternatively you can rebind zaw -- I use `bindkey '^@' zaw` to bind it to `control+space`.  You can call `zaw`, `zaw-history`, or any other zle widget with `M-x` (`alt+x`), which gives you a prompt to type a zle widget name.  So `M-x zaw-history` will run zaw-history.  Or you could bind `zaw-history` to a key with something like `bindkey '^n' zaw-history`.

**Comment by brandonsturgeon** [comment]
Oh jeeze that's embarrassing. 

Well I got zaw to work. It seems I can't bind it to `^r`, though. Any cool trick to be able to do that? I don't want zsh's `bck-i-search` anymore, now that I have Zaw.

**Comment by willghatch** [comment]
`bindkey '^r' zaw-history` works for me.

**Comment by brandonsturgeon** [comment]
I have that too, but `^r` just triggers zsh's `bck-i-search`. Bummer.

**Comment by adambhun** [comment]
Try appending `eval bindkey '^r' zaw-history` to your .zshrc file.
