### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by willghatch** [zsh-users/zaw#92]
I've been maintaining zaw (read: accepting pull requests) for some time, but I don't think I really have time for it anymore.  I mostly don't use zsh anymore since I'm building and using [rash](https://github.com/willghatch/racket-rash) (which doesn't currently have any of the advantages of an extensible editor like zsh does, but eventually I plan on it).

Sorry I'm probably not going to fix any more zaw issues going forward.

**Comment by termoshtt** [comment]
Sorry for my little cooperation. I'm still using zaw everyday, and I will do more maintenance.
