### ISSUE TITLE
Error when using `zsh-syntax-hightlighting` with `zaw`

### ISSUE THREAD

**Issue by magthe** [zsh-users/zaw#93]
When using the following configuration (`~/.zshrc`):

```
HISTSIZE=5000
SAVEHIST=2500
HISTFILE=~/.zhist
source ~/.zplug/init.zsh
zstyle :filter-select hist-find-no-dups yes
zplug zsh-users/zaw
zplug zsh-users/zsh-syntax-highlighting, defer:2
zplug load
bindkey '^R' zaw-history
```

and I do the following:

1. Press CTRL-R to open `zaw`'s interactive history search
2. Press enter on the first history item to run it

I get the following error:

```
_zsh_highlight:17: bad set of key/value pairs for associative array
```

If I remove the line `zstyle :filter-select hist-find-no-dups yes` from my configuration the error message stops appearing.

**Comment by termoshtt** [comment]
Thanks for report!

https://github.com/zsh-users/zsh-syntax-highlighting/issues/500#issuecomment-360765678
> The cause is that zaw creates a variable named options, hiding clashing with the variable of the same name provided by zsh itself via a standard module.

This will be true. I confirm this error cease to happen when `options` is renamed.

**Comment by danielshahaf** [comment]
@termoshtt Thanks for fixing this on your end.
